global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'ubuntu'
    static_configs:
      - targets: ['192.168.1.4:9100','192.168.1.5:9100']
  - job_name: 'win-exporter'
    static_configs:
      - targets: ['192.168.1.21:9182']
  - job_name: 'docker'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9323','192.168.1.4:9323','192.168.1.5:9323']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080','192.168.1.4:8080','192.168.1.5:8080']
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.1.8
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.10:9116
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
alerting:
  alertmanagers:
    - static_configs:
      - targets: [ 'localhost:9093' ]
rule_files:
- "/alertmanager/alert.rules.yml"
